namespace OpenWhoop.App
{
    // From Rust: pub enum PacketType
    public enum PacketType : byte
    {
        Command = 35,
        CommandResponse = 36,
        RealtimeData = 40,
        HistoricalData = 47,
        RealtimeRawData = 43,
        Event = 48,
        Metadata = 49,
        ConsoleLogs = 50,
        RealtimeImuDataStream = 51,
        HistoricalImuDataStream = 52,
    }

    // From Rust: pub enum MetadataType
    public enum MetadataType : byte
    {
        HistoryStart = 1,
        HistoryEnd = 2,
        HistoryComplete = 3,
    }

    // From Rust: pub enum EventNumber
    public enum EventNumber : byte
    {
        Undefined = 0,
        Error = 1,
        ConsoleOutput = 2,
        BatteryLevel = 3,
        SystemControl = 4,
        External5vOn = 5,
        External5vOff = 6,
        ChargingOn = 7,
        ChargingOff = 8,
        WristOn = 9,
        WristOff = 10,
        BleConnectionUp = 11,
        BleConnectionDown = 12,
        RtcLost = 13,
        DoubleTap = 14,
        Boot = 15,
        SetRtc = 16,
        TemperatureLevel = 17,
        PairingMode = 18,
        SerialHeadConnected = 19,
        SerialHeadRemoved = 20,
        BatteryPackConnected = 21,
        BatteryPackRemoved = 22,
        BleBonded = 23,
        BleHrProfileEnabled = 24,
        BleHrProfileDisabled = 25,
        TrimAllData = 26,
        TrimAllDataEnded = 27,
        FlashInitComplete = 28,
        StrapConditionReport = 29,
        BootReport = 30,
        ExitVirginMode = 31,
        CaptouchAutothresholdAction = 32,
        BleRealtimeHrOn = 33,
        BleRealtimeHrOff = 34,
        AccelerometerReset = 35,
        AfeReset = 36,
        ShipModeEnabled = 37,
        ShipModeDisabled = 38,
        ShipModeBoot = 39,
        Ch1SaturationDetected = 40,
        Ch2SaturationDetected = 41,
        AccelerometerSaturationDetected = 42,
        BleSystemReset = 43,
        BleSystemOn = 44,
        BleSystemInitialized = 45,
        RawDataCollectionOn = 46,
        RawDataCollectionOff = 47,
        Rebooting = 48, //Guessing as this is seen when reboot commands are sent
        StrapDrivenAlarmSet = 56,
        StrapDrivenAlarmExecuted = 57,
        AppDrivenAlarmExecuted = 58,
        StrapDrivenAlarmDisabled = 59,
        HapticsFired = 60,
        ExtendedBatteryInformation = 63,
        HighFreqSyncPrompt = 96,
        HighFreqSyncEnabled = 97,
        HighFreqSyncDisabled = 98,
        HapticsTerminated = 100,
    }

    public enum CommandNumber : byte
    {
        LinkValid = 1,
        GetMaxProtocolVersion = 2,
        ToggleRealtimeHr = 3,
        ReportVersionInfo = 7,
        ToggleR7DataCollection = 16,
        SetClock = 10,
        GetClock = 11,
        ToggleGenericHrProfile = 14,
        RunHapticPatternMaverick = 19,
        AbortHistoricalTransmits = 20,
        SendHistoricalData = 22,
        HistoricalDataResult = 23,
        GetBatteryLevel = 26,
        RebootStrap = 29,
        ForceTrim = 25,
        PowerCycleStrap = 32,
        SetReadPointer = 33,
        GetDataRange = 34,
        GetHelloHarvard = 35, 
        StartFirmwareLoad = 36,
        LoadFirmwareData = 37,
        ProcessFirmwareImage = 38,
        StartFirmwareLoadNew = 142,
        LoadFirmwareDataNew = 143,
        ProcessFirmwareImageNew = 144,
        VerifyFirmwareImage = 83,
        SetLedDrive = 39,
        GetLedDrive = 40,
        SetTiaGain = 41,
        GetTiaGain = 42,
        SetBiasOffset = 43,
        GetBiasOffset = 44,
        EnterBleDfu = 45,
        SetDpType = 52,
        ForceDpType = 53,
        SendR10R11Realtime = 63,
        SetAlarmTime = 66,
        GetAlarmTime = 67,
        RunAlarm = 68,
        DisableAlarm = 69,
        GetAdvertisingNameHarvard = 76,
        SetAdvertisingNameHarvard = 77,
        RunHapticsPattern = 79,
        GetAllHapticsPattern = 80,
        StartRawData = 81,
        StopRawData = 82,
        GetBodyLocationAndStatus = 84,
        EnterHighFreqSync = 96,
        ExitHighFreqSync = 97,
        GetExtendedBatteryInfo = 98,
        ResetFuelGauge = 99,
        CalibrateCapsense = 100,
        ToggleImuModeHistorical = 105,
        ToggleImuMode = 106,
        ToggleOpticalMode = 108,
        EnableOpticalData = 107,
        StartFfKeyExchange = 117,
        SendNextFf = 118,
        SetFfValue = 120,
        GetFfValue = 128,
        StopHaptics = 122,
        SelectWrist = 123,
        ToggleLabradorFiltered = 139,
        ToggleLabradorRawSave = 125,
        ToggleLabradorDataGeneration = 124,
        StartDeviceConfigKeyExchange = 115,
        SendNextDeviceConfig = 116,
        SetDeviceConfigValue = 119,
        GetDeviceConfigValue = 121,
        SetResearchPacket = 131,
        GetResearchPacket = 132,
        SetAdvertisingName = 140, // Added from Rust
        GetAdvertisingName = 141, // Added from Rust
        GetHello = 145, // Added from Rust
    }
}